### ISSUE TITLE
解决 readthedocs 中无法正常生成文档的问题

### ISSUE THREAD

**Issue by mozillazg** [mozillazg/aiobearychat#1]
readthedocs 不支持最新的 typing 语法，构建文档时会报语法错误：

https://readthedocs.org/projects/aiobearychat/builds/5858341/

```python
/home/docs/checkouts/readthedocs.org/user_builds/aiobearychat/checkouts/stable/docs/aiobearychat.rst:19: WARNING: autodoc: failed to import module 'aiobearychat.abc'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/aiobearychat/envs/stable/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 551, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/aiobearychat/checkouts/stable/aiobearychat/abc.py", line 6, in <module>
    from aiobearychat.sansio import Response, format_url
  File "/home/docs/checkouts/readthedocs.org/user_builds/aiobearychat/checkouts/stable/aiobearychat/sansio.py", line 11
    status: str = attr.ib()
          ^
SyntaxError: invalid syntax
/home/docs/checkouts/readthedocs.org/user_builds/aiobearychat/checkouts/stable/docs/aiobearychat.rst:35: WARNING: autodoc: failed to import module 'aiobearychat.sansio'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/aiobearychat/envs/stable/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 551, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/aiobearychat/checkouts/stable/aiobearychat/sansio.py", line 11
    status: str = attr.ib()
```

refer https://github.com/rtfd/readthedocs.org/issues/2581 https://github.com/rtfd/readthedocs.org/issues/2584

**Comment by mozillazg** [comment]
已通过 #6 解决
